import { promises as fsPromises } from "fs";
import os from "os";
import path from "path";
import type { ClawDevConfig } from "@clawdev/shared";
import { resolveClawDevConfigPath, resolveClawDevEnvPath } from "./paths.js";

function nonEmpty(value: string | null | undefined): string | null {
  return typeof value === "string" && value.trim().length > 0 ? value.trim() : null;
}

function expandHomePrefix(value: string): string {
  if (value === "~") return os.homedir();
  if (value.startsWith("~/")) return path.resolve(os.homedir(), value.slice(2));
  return value;
}

function resolveHomeAwarePath(value: string): string {
  return path.resolve(expandHomePrefix(value));
}

function sanitizeWorktreeInstanceId(rawValue: string): string {
  const trimmed = rawValue.trim().toLowerCase();
  const normalized = trimmed
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^[-_]+|[-_]+$/g, "");
  return normalized || "worktree";
}

function isLoopbackHost(hostname: string): boolean {
  const value = hostname.trim().toLowerCase();
  return value === "127.0.0.1" || value === "localhost" || value === "::1";
}

function rewriteLocalUrlPort(rawUrl: string | undefined, port: number): string | undefined {
  if (!rawUrl) return undefined;
  try {
    const parsed = new URL(rawUrl);
    if (!isLoopbackHost(parsed.hostname)) return rawUrl;
    parsed.port = String(port);
    return parsed.toString();
  } catch {
    return rawUrl;
  }
}

function parseEnvFile(contents: string): Record<string, string> {
  const entries: Record<string, string> = {};

  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const match = rawLine.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (!match) continue;

    const [, key, rawValue] = match;
    const value = rawValue.trim();
    if (!value) {
      entries[key] = "";
      continue;
    }

    if (
      (value.startsWith("\"") && value.endsWith("\"")) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      entries[key] = value.slice(1, -1);
      continue;
    }

    entries[key] = value.replace(/\s+#.*$/, "").trim();
  }

  return entries;
}

async function readEnvEntries(envPath: string): Promise<Record<string, string>> {
  if (!(await Bun.file(envPath).exists())) return {};
  return parseEnvFile(await Bun.file(envPath).text());
}

function formatEnvEntries(entries: Record<string, string>): string {
  return [
    "# ClawDev environment variables",
    "# Generated by ClawDev worktree repair",
    ...Object.entries(entries).map(([key, value]) => `${key}=${JSON.stringify(value)}`),
    "",
  ].join("\n");
}

function isPathInside(candidatePath: string, rootPath: string): boolean {
  const candidate = path.resolve(candidatePath);
  const root = path.resolve(rootPath);
  return candidate === root || candidate.startsWith(`${root}${path.sep}`);
}

type WorktreeRuntimeContext = {
  configPath: string;
  envPath: string;
  worktreeName: string;
  instanceId: string;
  homeDir: string;
  instanceRoot: string;
  contextPath: string;
  embeddedPostgresDataDir: string;
  backupDir: string;
  logDir: string;
  storageDir: string;
  secretsKeyFilePath: string;
};

function resolveWorktreeRuntimeContext(
  env: NodeJS.ProcessEnv,
  overrideConfigPath?: string,
): WorktreeRuntimeContext | null {
  if (env.CLAWDEV_IN_WORKTREE !== "true") return null;

  const configPath = resolveClawDevConfigPath(overrideConfigPath);
  const envPath = resolveClawDevEnvPath(configPath);
  const worktreeRoot = path.resolve(path.dirname(configPath), "..");
  const worktreeName = nonEmpty(env.CLAWDEV_WORKTREE_NAME) ?? path.basename(worktreeRoot);
  const instanceId = nonEmpty(env.CLAWDEV_INSTANCE_ID) ?? sanitizeWorktreeInstanceId(worktreeName);
  const homeDir = resolveHomeAwarePath(
    nonEmpty(env.CLAWDEV_HOME) ??
      nonEmpty(env.CLAWDEV_WORKTREES_DIR) ??
      "~/.clawdev-worktrees",
  );
  const instanceRoot = path.resolve(homeDir, "instances", instanceId);

  return {
    configPath,
    envPath,
    worktreeName,
    instanceId,
    homeDir,
    instanceRoot,
    contextPath: path.resolve(homeDir, "context.json"),
    embeddedPostgresDataDir: path.resolve(instanceRoot, "db"),
    backupDir: path.resolve(instanceRoot, "data", "backups"),
    logDir: path.resolve(instanceRoot, "logs"),
    storageDir: path.resolve(instanceRoot, "data", "storage"),
    secretsKeyFilePath: path.resolve(instanceRoot, "secrets", "master.key"),
  };
}

async function writeConfigFile(configPath: string, config: ClawDevConfig): Promise<void> {
  await Bun.write(configPath, JSON.stringify(config, null, 2) + "\n");
}

function resolveRepoManagedWorktreesRoot(worktreeRoot: string): string | null {
  const normalized = path.resolve(worktreeRoot);
  const marker = `${path.sep}.clawdev${path.sep}worktrees${path.sep}`;
  const index = normalized.indexOf(marker);
  if (index === -1) return null;
  const repoRoot = normalized.slice(0, index);
  return path.resolve(repoRoot, ".clawdev", "worktrees");
}

async function collectSiblingWorktreePorts(context: WorktreeRuntimeContext): Promise<{
  serverPorts: Set<number>;
  databasePorts: Set<number>;
}> {
  const serverPorts = new Set<number>();
  const databasePorts = new Set<number>();
  const siblingConfigPaths = new Set<string>();
  const instancesDir = path.resolve(context.homeDir, "instances");
  if (await Bun.file(instancesDir).exists()) {
    for (const entry of await fsPromises.readdir(instancesDir, { withFileTypes: true })) {
      if (!entry.isDirectory() || entry.name === context.instanceId) continue;

      const siblingConfigPath = path.resolve(instancesDir, entry.name, "config.json");
      if (await Bun.file(siblingConfigPath).exists()) {
        siblingConfigPaths.add(siblingConfigPath);
      }
    }
  }

  const repoManagedWorktreesRoot = resolveRepoManagedWorktreesRoot(path.dirname(context.configPath));
  if (repoManagedWorktreesRoot && (await Bun.file(repoManagedWorktreesRoot).exists())) {
    for (const entry of await fsPromises.readdir(repoManagedWorktreesRoot, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;

      const siblingConfigPath = path.resolve(repoManagedWorktreesRoot, entry.name, ".clawdev", "config.json");
      if (path.resolve(siblingConfigPath) === path.resolve(context.configPath)) continue;
      if (await Bun.file(siblingConfigPath).exists()) {
        siblingConfigPaths.add(siblingConfigPath);
      }
    }
  }

  for (const siblingConfigPath of siblingConfigPaths) {
    try {
      const siblingConfig = JSON.parse(await Bun.file(siblingConfigPath).text()) as ClawDevConfig;
      if (Number.isInteger(siblingConfig.server.port) && siblingConfig.server.port > 0) {
        serverPorts.add(siblingConfig.server.port);
      }
      if (
        siblingConfig.database.mode === "embedded-postgres" &&
        Number.isInteger(siblingConfig.database.embeddedPostgresPort) &&
        siblingConfig.database.embeddedPostgresPort > 0
      ) {
        databasePorts.add(siblingConfig.database.embeddedPostgresPort);
      }
    } catch {
      // Ignore sibling configs that are missing or malformed.
    }
  }

  return { serverPorts, databasePorts };
}

function findNextUnclaimedPort(preferredPort: number, claimedPorts: Set<number>): number {
  let port = Math.max(1, Math.trunc(preferredPort));
  while (claimedPorts.has(port)) {
    port += 1;
  }
  return port;
}

function buildIsolatedWorktreeConfig(
  config: ClawDevConfig,
  context: WorktreeRuntimeContext,
  portOverrides?: {
    serverPort?: number;
    databasePort?: number;
  },
): ClawDevConfig {
  const serverPort = portOverrides?.serverPort ?? config.server.port;
  const databasePort =
    config.database.mode === "embedded-postgres"
      ? portOverrides?.databasePort ?? config.database.embeddedPostgresPort
      : undefined;
  const nextConfig: ClawDevConfig = {
    ...config,
    database: {
      ...config.database,
      ...(config.database.mode === "embedded-postgres"
        ? {
            embeddedPostgresDataDir: context.embeddedPostgresDataDir,
            embeddedPostgresPort: databasePort ?? config.database.embeddedPostgresPort,
            backup: {
              ...config.database.backup,
              dir: context.backupDir,
            },
          }
        : {}),
    },
    server: {
      ...config.server,
      port: serverPort,
    },
    logging: {
      ...config.logging,
      logDir: context.logDir,
    },
    storage: {
      ...config.storage,
      localDisk: {
        ...config.storage.localDisk,
        baseDir: context.storageDir,
      },
    },
    secrets: {
      ...config.secrets,
      localEncrypted: {
        ...config.secrets.localEncrypted,
        keyFilePath: context.secretsKeyFilePath,
      },
    },
  };

  if (config.auth.baseUrlMode === "explicit" && config.auth.publicBaseUrl) {
    nextConfig.auth = {
      ...config.auth,
      publicBaseUrl: rewriteLocalUrlPort(config.auth.publicBaseUrl, serverPort),
    };
  }

  return nextConfig;
}

function needsWorktreeConfigRepair(
  config: ClawDevConfig,
  context: WorktreeRuntimeContext,
): boolean {
  if (config.database.mode === "embedded-postgres") {
    if (!isPathInside(config.database.embeddedPostgresDataDir, context.instanceRoot)) {
      return true;
    }
    if (!isPathInside(config.database.backup.dir, context.instanceRoot)) {
      return true;
    }
  }

  if (!isPathInside(config.logging.logDir, context.instanceRoot)) {
    return true;
  }
  if (!isPathInside(config.storage.localDisk.baseDir, context.instanceRoot)) {
    return true;
  }
  if (!isPathInside(config.secrets.localEncrypted.keyFilePath, context.instanceRoot)) {
    return true;
  }

  return false;
}

export function applyRuntimePortSelectionToConfig(
  config: ClawDevConfig,
  input: {
    serverPort: number;
    databasePort?: number | null;
    allowServerPortWrite?: boolean;
    allowDatabasePortWrite?: boolean;
  },
): { config: ClawDevConfig; changed: boolean } {
  let changed = false;
  let nextConfig = config;

  if (input.allowServerPortWrite !== false && config.server.port !== input.serverPort) {
    nextConfig = {
      ...nextConfig,
      server: {
        ...nextConfig.server,
        port: input.serverPort,
      },
    };
    changed = true;
  }

  if (
    input.allowDatabasePortWrite !== false &&
    nextConfig.database.mode === "embedded-postgres" &&
    typeof input.databasePort === "number" &&
    nextConfig.database.embeddedPostgresPort !== input.databasePort
  ) {
    nextConfig = {
      ...nextConfig,
      database: {
        ...nextConfig.database,
        embeddedPostgresPort: input.databasePort,
      },
    };
    changed = true;
  }

  if (nextConfig.auth.baseUrlMode === "explicit" && nextConfig.auth.publicBaseUrl) {
    const rewritten = rewriteLocalUrlPort(nextConfig.auth.publicBaseUrl, input.serverPort);
    if (rewritten && rewritten !== nextConfig.auth.publicBaseUrl) {
      nextConfig = {
        ...nextConfig,
        auth: {
          ...nextConfig.auth,
          publicBaseUrl: rewritten,
        },
      };
      changed = true;
    }
  }

  return { config: nextConfig, changed };
}

export async function maybeRepairLegacyWorktreeConfigAndEnvFiles(): Promise<{
  repairedConfig: boolean;
  repairedEnv: boolean;
}> {
  const context = resolveWorktreeRuntimeContext(process.env);
  if (!context) {
    return { repairedConfig: false, repairedEnv: false };
  }

  process.env.CLAWDEV_HOME = context.homeDir;
  process.env.CLAWDEV_INSTANCE_ID = context.instanceId;
  process.env.CLAWDEV_CONFIG = context.configPath;
  process.env.CLAWDEV_CONTEXT = context.contextPath;
  process.env.CLAWDEV_WORKTREE_NAME = context.worktreeName;

  let repairedConfig = false;
  if (await Bun.file(context.configPath).exists()) {
    try {
      const parsed = JSON.parse(await Bun.file(context.configPath).text()) as ClawDevConfig;
      const siblingPorts = await collectSiblingWorktreePorts(context);
      const hasSiblingPortCollision =
        siblingPorts.serverPorts.has(parsed.server.port) ||
        (parsed.database.mode === "embedded-postgres" &&
          siblingPorts.databasePorts.has(parsed.database.embeddedPostgresPort));

      if (needsWorktreeConfigRepair(parsed, context) || hasSiblingPortCollision) {
        const selectedServerPort = findNextUnclaimedPort(
          parsed.server.port === 3100 ? 3101 : parsed.server.port,
          siblingPorts.serverPorts,
        );
        const selectedDatabasePort =
          parsed.database.mode === "embedded-postgres"
            ? findNextUnclaimedPort(
                parsed.database.embeddedPostgresPort === 54329
                  ? 54330
                  : parsed.database.embeddedPostgresPort,
                new Set([...siblingPorts.databasePorts, selectedServerPort]),
              )
            : undefined;

        await writeConfigFile(
          context.configPath,
          buildIsolatedWorktreeConfig(parsed, context, {
            serverPort: selectedServerPort,
            databasePort: selectedDatabasePort,
          }),
        );
        repairedConfig = true;
      }
    } catch {
      // Leave invalid configs to the normal startup validation path.
    }
  }

  const existingEnvEntries = await readEnvEntries(context.envPath);
  const desiredEnvEntries: Record<string, string> = {
    ...existingEnvEntries,
    CLAWDEV_HOME: context.homeDir,
    CLAWDEV_INSTANCE_ID: context.instanceId,
    CLAWDEV_CONFIG: context.configPath,
    CLAWDEV_CONTEXT: context.contextPath,
    CLAWDEV_IN_WORKTREE: "true",
    CLAWDEV_WORKTREE_NAME: context.worktreeName,
  };

  const repairedEnv = Object.entries(desiredEnvEntries).some(
    ([key, value]) => existingEnvEntries[key] !== value,
  );

  if (repairedEnv) {
    await Bun.write(context.envPath, formatEnvEntries(desiredEnvEntries));
  }

  return { repairedConfig, repairedEnv };
}

export async function maybePersistWorktreeRuntimePorts(input: {
  serverPort: number;
  databasePort?: number | null;
}): Promise<void> {
  const context = resolveWorktreeRuntimeContext(process.env);
  if (!context || !(await Bun.file(context.configPath).exists())) return;

  let fileConfig: ClawDevConfig;
  try {
    fileConfig = JSON.parse(await Bun.file(context.configPath).text()) as ClawDevConfig;
  } catch {
    return;
  }

  const { config, changed } = applyRuntimePortSelectionToConfig(fileConfig, {
    serverPort: input.serverPort,
    databasePort: input.databasePort,
    allowServerPortWrite: !nonEmpty(process.env.PORT),
    allowDatabasePortWrite: !nonEmpty(process.env.DATABASE_URL),
  });

  if (changed) {
    await writeConfigFile(context.configPath, config);
  }
}
